# Generated by Django 4.2.11 on 2024-04-13 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0005_remove_formapago_usuarios_alter_campania_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True, null=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.formapago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'st_formas_pago_usuarios',
            },
        ),
    ]
