# Generated by Django 4.2.11 on 2024-04-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_formapagousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
