# Generated by Django 4.2.11 on 2024-04-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_beneficiario_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapagousuario',
            options={'verbose_name': 'Forma de Pago por Usuario', 'verbose_name_plural': 'Formas de Pago por Usuario'},
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha_cierre',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
