# Generated by Django 4.2.11 on 2024-04-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0009_historialpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpago',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='fecha_ult_act',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
