# Generated by Django 4.2.11 on 2024-04-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0010_historialpago_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='iamgen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
