# Generated by Django 4.2.11 on 2024-04-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_formapago_iamgen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapago',
            old_name='iamgen',
            new_name='imagen',
        ),
    ]
