# Generated by Django 4.2.11 on 2024-05-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0012_rename_iamgen_formapago_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpago',
            name='campania',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.campania'),
        ),
    ]
