# Generated by Django 4.2.11 on 2024-05-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0013_historialpago_campania'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
