# Generated by Django 4.2.11 on 2024-05-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0014_campania_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
