# Generated by Django 4.2.11 on 2024-05-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0016_solcampania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solcampania',
            name='categorias',
        ),
        migrations.AddField(
            model_name='solcampania',
            name='categorias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.categoria'),
        ),
    ]
